Fix for benchmarking nits (#855)
This PR contains benchmarking nits and fixes.

- [x] For Polkadot and `pallet_bags_list` where benchmarks fails for
`AutoRebagNumber = 0`
(https://github.com/polkadot-fellows/runtimes/actions/runs/17017979638/job/48243408516)
  - possibly we could also fix the benchmark itself
- [x] Probably funds and KeyDeposit related
https://github.com/polkadot-fellows/runtimes/actions/runs/16988940719/job/48163751298
```
The following 3 benchmarks failed:
- pallet_session::purge_keys
- pallet_session::set_keys
- runtime_parachains::disputes::slashing::report_dispute_lost_unsigned
Error: Input("3 benchmarks failed")
```
- [ ] `promote_fast` - rewrites u16 to u32 which does not compile
- probably needs polkadot-sdk fix (need to investigate and create
polkadot-sdk issue)

<!-- Remember that you can run `/merge` to enable auto-merge in the PR
-->

<!-- Remember to modify the changelog. If you don't need to modify it,
you can check the following box.
Instead, if you have already modified it, simply delete the following
line. -->

- [X] Does not require a CHANGELOG entry

---------

Co-authored-by: Kian Paimani <5588131+kianenigma@users.noreply.github.com>