Resolve conflicts (#988)
@clangenb there are a couple of Encointer errors:

```
error[E0599]: no function or associated item named `convert` found for struct `EncointerBalanceConverter` in the current scope
   --> /Users/claravanstaden/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/pallet-encointer-balances-20.2.1/src/impl_fungibles.rs:27:29
    |
27  |     EncointerBalanceConverter::convert(balance)
    |                                ^^^^^^^ function or associated item not found in `EncointerBalanceConverter`
    |
note: there are multiple different versions of crate `sp_runtime` in the dependency graph
```

---------

Co-authored-by: Rodrigo Quelhas <22591718+RomarQ@users.noreply.github.com>
Co-authored-by: Branislav Kontur <bkontur@gmail.com>
Co-authored-by: GitHub Action <action@github.com>
Co-authored-by: Ron <yrong1997@gmail.com>
Co-authored-by: Kian Paimani <5588131+kianenigma@users.noreply.github.com>
Co-authored-by: Dónal Murray <donalm@seadanda.dev>
Co-authored-by: Adrian Catangiu <adrian@parity.io>